import type { ClaimState, Program, RepositoryType } from "@/lib/types";

export const programs: Program[] = [
  {
    claimState: "Claimed",
    custody: {
      asset: "USDC",
      chain: "Ethereum",
      currentApr: 4.1,
      executionPolicy: "Delay modifier plus guardian Safe",
      strategy: "Compound III supply",
    },
    description:
      "App Router, React infrastructure, and the framework surface a large security and reliability blast radius.",
    donors: 422,
    id: "nextjs",
    language: "TypeScript",
    openBounties: 17,
    owner: "vercel",
    payoutAuthority: "Dual control",
    repo: "next.js",
    repositoryType: "Framework",
    slug: "vercel-next-js",
    stars: 131_000,
    tags: ["frontend", "framework", "critical dependency"],
    totalFundedUsd: 184_500,
  },
  {
    claimState: "Unclaimed",
    custody: {
      asset: "USDC",
      chain: "Ethereum",
      currentApr: null,
      executionPolicy: "OSSTrust-managed payout multisig",
      strategy: "Idle Safe buffer",
    },
    description:
      "One of the most depended-on transport stacks on the internet, but still a project donors can fund before maintainers opt in.",
    donors: 255,
    id: "curl",
    language: "C",
    openBounties: 11,
    owner: "curl",
    payoutAuthority: "Marketplace",
    repo: "curl",
    repositoryType: "Infrastructure",
    slug: "curl-curl",
    stars: 39_800,
    tags: ["networking", "infrastructure", "oss staple"],
    totalFundedUsd: 118_900,
  },
  {
    claimState: "Claimed",
    custody: {
      asset: "USDC",
      chain: "Ethereum",
      currentApr: 4.3,
      executionPolicy: "Repo owner Safe with challenge window",
      strategy: "Compound III supply",
    },
    description:
      "Utility-first CSS is deeply embedded in production web apps, making a visible, high-trust bounty pool attractive to donors.",
    donors: 301,
    id: "tailwindcss",
    language: "TypeScript",
    openBounties: 8,
    owner: "tailwindlabs",
    payoutAuthority: "Repo owner",
    repo: "tailwindcss",
    repositoryType: "Framework",
    slug: "tailwindlabs-tailwindcss",
    stars: 87_500,
    tags: ["css", "frontend", "design systems"],
    totalFundedUsd: 102_400,
  },
  {
    claimState: "Claimed",
    custody: {
      asset: "USDC",
      chain: "Ethereum",
      currentApr: 4.0,
      executionPolicy: "Delay modifier plus guardian Safe",
      strategy: "Compound III supply",
    },
    description:
      "Critical linting infrastructure with a huge downstream footprint and a natural stream of bug and rule-bypass reports.",
    donors: 209,
    id: "eslint",
    language: "JavaScript",
    openBounties: 9,
    owner: "eslint",
    payoutAuthority: "Dual control",
    repo: "eslint",
    repositoryType: "Developer Tool",
    slug: "eslint-eslint",
    stars: 26_700,
    tags: ["tooling", "static analysis", "developer workflow"],
    totalFundedUsd: 91_300,
  },
  {
    claimState: "Unclaimed",
    custody: {
      asset: "USDC",
      chain: "Ethereum",
      currentApr: null,
      executionPolicy: "OSSTrust-managed payout multisig",
      strategy: "Idle Safe buffer",
    },
    description:
      "The canonical Bitcoin node implementation draws donors even without direct maintainer participation.",
    donors: 180,
    id: "bitcoin",
    language: "C++",
    openBounties: 6,
    owner: "bitcoin",
    payoutAuthority: "Marketplace",
    repo: "bitcoin",
    repositoryType: "Security",
    slug: "bitcoin-bitcoin",
    stars: 84_900,
    tags: ["protocol", "security", "payments"],
    totalFundedUsd: 78_600,
  },
  {
    claimState: "Claimed",
    custody: {
      asset: "USDC",
      chain: "Ethereum",
      currentApr: 3.9,
      executionPolicy: "Repo owner Safe with challenge window",
      strategy: "Compound III supply",
    },
    description:
      "Package-manager infrastructure with direct impact on the JavaScript supply chain and developer build systems.",
    donors: 193,
    id: "pnpm",
    language: "TypeScript",
    openBounties: 13,
    owner: "pnpm",
    payoutAuthority: "Repo owner",
    repo: "pnpm",
    repositoryType: "Developer Tool",
    slug: "pnpm-pnpm",
    stars: 31_600,
    tags: ["package manager", "javascript", "supply chain"],
    totalFundedUsd: 73_100,
  },
  {
    claimState: "Unclaimed",
    custody: {
      asset: "USDC",
      chain: "Ethereum",
      currentApr: null,
      executionPolicy: "OSSTrust-managed payout multisig",
      strategy: "Idle Safe buffer",
    },
    description:
      "Core Go Ethereum infrastructure with obvious demand for protocol-facing bounty workflows and higher-signal disclosures.",
    donors: 147,
    id: "geth",
    language: "Go",
    openBounties: 5,
    owner: "ethereum",
    payoutAuthority: "Marketplace",
    repo: "go-ethereum",
    repositoryType: "Infrastructure",
    slug: "ethereum-go-ethereum",
    stars: 49_900,
    tags: ["ethereum", "execution client", "protocol"],
    totalFundedUsd: 66_800,
  },
  {
    claimState: "Claimed",
    custody: {
      asset: "USDC",
      chain: "Ethereum",
      currentApr: 4.2,
      executionPolicy: "Delay modifier plus guardian Safe",
      strategy: "Compound III supply",
    },
    description:
      "A small, sharp CLI utility with a huge installation base and a bounty pool that benefits from fast maintainer approval.",
    donors: 124,
    id: "jq",
    language: "C",
    openBounties: 4,
    owner: "jqlang",
    payoutAuthority: "Dual control",
    repo: "jq",
    repositoryType: "Developer Tool",
    slug: "jqlang-jq",
    stars: 31_900,
    tags: ["cli", "data tooling", "unix"],
    totalFundedUsd: 52_500,
  },
];

export const claimStateOptions: ClaimState[] = ["Claimed", "Unclaimed"];

export const repositoryTypeOptions: RepositoryType[] = [
  "Developer Tool",
  "Framework",
  "Infrastructure",
  "Library",
  "Security",
];
